Scenario: AI System for Detecting Lung Diseases from Chest X-rays
🚨 The Problem

A large hospital receives thousands of chest X-rays daily.

Radiologists are:

Overworked

Limited in number

Required to make fast decisions

Sometimes critical conditions like:

👉 Pneumonia
👉 COVID-19
👉 Normal lungs

must be identified within minutes.

Delays can cost lives.

💡 The Solution: Build an AI Assistant

The hospital decides to deploy an AI model that can pre-screen X-rays and
alert doctors.

But there is a challenge…

❗ Medical datasets are usually SMALL.

Training a deep neural network from scratch would require:

Millions of labeled X-rays

Massive GPU clusters

Months of training

Not practical.

⭐ Enter Transfer Learning (Your Code)

Instead of starting from zero, engineers use:

👉 ResNet50 trained on ImageNet

Although ImageNet contains everyday objects (dogs, cars, etc.),
the early CNN layers learn universal visual patterns, like:

✅ Edges
✅ Gradients
✅ Textures
✅ Shapes

These features are also present in medical scans.

In [4]:
import torchvision.models as models
from torch import nn # neural network
# Load a pretrained ResNet50 model
model = models.resnet50(pretrained=True)
# freeze all pretrained layer
for param in model.parameters():
    param.requires_grad = False
# modify the final classification layer
num_classes = 3
# count the number of trainable layer
model.fc = nn.Linear(model.fc.in_features, num_classes)
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Trainable Params : {trainable_params}")

Trainable Params : 6147

Scenario: AI System for Detecting Fraud in Financial Transactions
🚨 The Problem
A major bank processes millions of transactions daily.
Fraud analysts are:
- Overwhelmed by the sheer volume
- Limited in number
- Required to make instant decisions
- Missing subtle fraud patterns hidden in massive datasets
Critical cases like:
👉 Credit card fraud
👉 Money laundering
👉 Normal transactions
must be flagged in real-time.
Delays can cost millions and damage customer trust.

💡 The Solution: Build an AI Assistant
The bank deploys an AI model that can pre-screen transactions and alert analysts.
But here’s the challenge…
❗ Fraud datasets are usually imbalanced and small.
Training a deep neural network from scratch would require:
- Billions of labeled transactions
- Huge compute clusters
- Months of training
Not practical.

⭐ Enter Transfer Learning (Your Code)
Instead of starting from zero, engineers use:
👉 BERT (Bidirectional Encoder Representations from Transformers) trained on massive text corpora.
Although BERT was trained on general language (Wikipedia, books, etc.), its early layers learn universal text patterns, like:
- ✅ Word embeddings
- ✅ Sentence structures
- ✅ Semantic relationships
- ✅ Contextual meaning
These features are also present in transaction descriptions, merchant details, and customer behavior logs.
By fine-tuning BERT on the bank’s fraud dataset, the AI can quickly learn to distinguish:
- Suspicious vs. normal transactions
- Fraud rings vs. genuine customer activity

⚡ Just like ResNet50 helps radiologists with X-rays, BERT helps fraud analysts with transaction logs —
both leveraging transfer learning to solve problems where data is scarce but decisions are critical.

In [11]:
from torch import nn
from transformers import BertForSequenceClassification

# load bert for classification

model = BertForSequenceClassification.from_pretrained(
    'bert-base-uncased',
)

# freeze all pretrained layers
for param in model.parameters():
    param.requires_grad = False

# COUNT trainable params
model.classifier = nn.Linear(model.config.hidden_size,3)
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Trainable Params : {trainable_params}")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: bert-base-uncased
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
classifier.weight                          | MISSING    |
classifier.bias                            | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Trainable Params : 2307

In [19]:
import torch
from torch import nn
from transformers import GPT2ForSequenceClassification

model = GPT2ForSequenceClassification.from_pretrained(
    "gpt2",
    num_labels=3
)

# Freeze GPT backbone only
for param in model.parameters():
    param.requires_grad = False

# Count trainable
model.classifier = nn.Linear(model.config.hidden_size,3)
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"Trainable Params : {trainable_params}")

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2ForSequenceClassification LOAD REPORT from: gpt2
Key          | Status  |
-------------+---------+-
score.weight | MISSING |

Notes:
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Trainable Params : 2307

 The Solution: Build an AI Assistant
The university deploys an AI model that can pre-screen essays and alert professors about suspicious content.
But here’s the challenge…
❗ Academic plagiarism datasets are usually small and domain-specific.
Training a deep NLP model from scratch would require:
- Millions of labeled essays
- Huge compute resources
- Months of training
Not practical.

⭐ Enter Transfer Learning (Your Code)
Instead of starting from zero, engineers use:
👉 GPT-style language models trained on massive text corpora (books, articles, Wikipedia).
Although these corpora contain general language, the early layers learn universal text features, like:
- ✅ Grammar patterns
- ✅ Semantic meaning
- ✅ Sentence structures
- ✅ Contextual relationships
These features are also present in student essays.
By fine-tuning the model on a smaller plagiarism dataset, the AI can quickly learn to distinguish:
- Original vs. copied content
- Paraphrased vs. genuinely written text
- Citation misuse vs. proper referencing

⚡ Just like ResNet50 helps radiologists with X-rays, and BERT helps fraud analysts with transactions, GPT-style models help
educators with essays — all leveraging transfer learning to solve problems where data is scarce but accuracy is critical.

In [1]:
from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments, Trainer
from datasets import Dataset
from peft import get_peft_model, LoraConfig

model_name = "gpt2"

model = AutoModelForCausalLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model.config.pad_token_id = tokenizer.pad_token_id
model.config.use_cache = False

lora_config = LoraConfig(
    r=8,   # rand of low rand matrices smaller = faster
    lora_alpha=32, # scaling factor
    lora_dropout=0.1, # dropout for regularization
    bias="none",
    task_type="CAUSAL_LM",  # next token prediction
    target_modules=["c_attn"]
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

train_texts = ["Hello world", "LoRA fine-tuning is fun", "Transformers are powerful"]
eval_texts = ["Testing evaluation", "Another sample"]

train_dataset = Dataset.from_dict({"text": train_texts})
eval_dataset = Dataset.from_dict({"text": eval_texts})

def tokenize_function(examples):
    tokens = tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=64
    )
    tokens["labels"] = tokens["input_ids"].copy()
    return tokens

train_dataset = train_dataset.map(tokenize_function, batched=True)
eval_dataset = eval_dataset.map(tokenize_function, batched=True)

train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
eval_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

training_args = TrainingArguments(
    output_dir="./lora-finetuned-model",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    num_train_epochs=1,
    logging_steps=1,
    save_strategy="epoch",
    eval_strategy="epoch",
    fp16=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset
)

trainer.train()

model.save_pretrained("./lora-weights")

print("Training complete. LoRA weights saved")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

C:\Users\singh\Desktop\DataScience_Training\.venv\Lib\site-packages\peft\tuners\lora\layer.py:2285: UserWarning: fan_in_fan_out is set to False but the target module is `Conv1D`. Setting fan_in_fan_out to True.
  warnings.warn(

trainable params: 294,912 || all params: 124,734,720 || trainable%: 0.2364

Map:   0%|          | 0/3 [00:00<?, ? examples/s]

Map:   0%|          | 0/2 [00:00<?, ? examples/s]

C:\Users\singh\Desktop\DataScience_Training\.venv\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Training complete. LoRA weights saved 🚀

Scenario: Fraud Detection in Customer Support Chats
- Problem: Fraudsters often contact bank support pretending to be customers, trying to reset passwords or gain access.
- Challenge: Analysts can’t manually read millions of chat transcripts.
- Solution: Use LoRA fine‑tuning on a pretrained language model (like distilbert-base-uncased) to classify chats as:
- 0 → Normal inquiry
- 1 → Fraud attempt
- 2 → Suspicious but unclear

In [4]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, TrainingArguments, Trainer
from datasets import Dataset
from peft import get_peft_model, LoraConfig, TaskType

# 1. Load model + tokenizer
model_name = "distilbert-base-uncased"

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=3   # 3 classes: Normal, Fraud, Suspicious
)

tokenizer = AutoTokenizer.from_pretrained(model_name)

# 2. LoRA config (for classification)
lora_config = LoraConfig(
    r=8,
    lora_alpha=32,
    lora_dropout=0.1,
    bias="none",
    task_type=TaskType.SEQ_CLS,   # 🔥 IMPORTANT CHANGE
    target_modules=["q_lin", "v_lin"]  # DistilBERT attention layers
)

# Apply LoRA
model = get_peft_model(model, lora_config)

# Print trainable params
model.print_trainable_parameters()

# 3. Dataset (Fraud chat examples)
train_data = {
    "text": [
        "I forgot my password can you help me",
        "Reset my account now urgent I lost access",
        "My card was declined why",
        "I need access to this account immediately change email",
        "Can you check my last transaction"
    ],
    "label": [0, 1, 0, 1, 2]   # 0=Normal, 1=Fraud, 2=Suspicious
}

eval_data = {
    "text": [
        "Help me update my phone number",
        "Urgent reset password now"
    ],
    "label": [0, 1]
}

train_dataset = Dataset.from_dict(train_data)
eval_dataset = Dataset.from_dict(eval_data)

# 4. Tokenization
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        padding="max_length",
        max_length=64
    )

train_dataset = train_dataset.map(tokenize_function, batched=True)
eval_dataset = eval_dataset.map(tokenize_function, batched=True)

# Rename label column for Trainer
train_dataset = train_dataset.rename_column("label", "labels")
eval_dataset = eval_dataset.rename_column("label", "labels")

# Set format
train_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])
eval_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

# 5. Training config
training_args = TrainingArguments(
    output_dir="./fraud-lora-model",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    num_train_epochs=3,
    logging_steps=1,
    save_strategy="epoch",
    eval_strategy="epoch",   # (your version-compatible)
    fp16=True
)

# 6. Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset
)

# 7. Train
trainer.train()

# 8. Save LoRA weights
model.save_pretrained(".weights/fraud-lora-weights")

print("✅ Fraud detection model trained & saved 🚀")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
pre_classifier.bias     | MISSING    |
classifier.bias         | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

trainable params: 740,355 || all params: 67,696,134 || trainable%: 1.0936

Map:   0%|          | 0/5 [00:00<?, ? examples/s]

Map:   0%|          | 0/2 [00:00<?, ? examples/s]

C:\Users\singh\Desktop\DataScience_Training\.venv\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

C:\Users\singh\Desktop\DataScience_Training\.venv\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)
C:\Users\singh\Desktop\DataScience_Training\.venv\Lib\site-packages\torch\utils\data\dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

✅ Fraud detection model trained & saved 🚀